backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/entity/SpecificationEntity.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/dto/SpecificationDto.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/mapper/converter/SpecificationConverter.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataService.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SynchronizationService.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/entity/Specification.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/database/SpecificationEntityUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/mapper/converter/SpecificationConverterTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataServiceTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SynchronizationServiceTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/service/SpecificationDatabaseServiceUnitTest.kt, backend/src/test/resources/data.sql
Parse the description from the OpenAPI-Specification and store it as metadata of the specification in ApiCenter.
Signed-off-by: Alexander Kaserbacher <alexander.kaserbacher@tngtech.com>
=> Add description to metadata.

backend/build.gradle, backend/src/main/kotlin/com/tngtech/apicenter/backend/config/WebConfiguration.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/dto/SpecificationFileDto.kt, backend/src/main/resources/api-definition.json
Removes Springfox and all annotations for OpenAPI-Documentation in controllers and DTOs - and adds an explicit OpenAPI-File.
=> Add api definition

backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/entity/SpecificationEntity.kt
Remove GeneratedValue annotation in order to not unnecessarily generate the UUID a second time and causing the POST /specification endpoint to return the wrong id.
=> Remove GeneratedValue annotation from UUID in specification entity.

frontend/src/app/specification-search-detail/specification-search-detail.component.html
After clicking around the website, it seems that there was never an
Angular route configured for `specifications/:specificationId`. However in
the specification search, this was the router link used when a user
clicked on a specification matching the search string. As Angular had no
route configured, clicking just returned the webapp to the home route
('/').
This change replaces that non-existent route with the page of the most
recent version of the specification.
Signed-off-by: Philippa Hack <philippa.hack@tngtech.com>
=> Correct specification route

backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerIntegrationTest.kt, backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionControllerIntegrationTest.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/config/SecurityConfiguration.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/config/WebConfiguration.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/service/SpecificationDatabaseService.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/service/VersionDatabaseService.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SessionController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SharedRestControllerExceptions.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/handler/SpecificationHandler.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/handler/VersionHandler.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/service/VersionPersistenceService.kt, backend/src/main/resources/api-definition.json, frontend/src/app/specification-overview/specification-overview.component.ts, frontend/src/app/specification-version/specification-version.component.html, frontend/src/app/specification-version/specification-version.component.ts, frontend/src/app/specification.service.spec.ts, frontend/src/app/version.service.ts, frontend/src/environments/environment.localhost.ts, frontend/src/environments/environment.prod.ts, frontend/src/environments/environment.ts
Two related changes here to do with the API
Firstly, modifies Spring config to route all HTTP requests to Angular. Before, every route within Angular's SPA had to be accessed from the root; if the user refreshed the page or sent a static link to someone, Spring would return 404.
Secondly, because both API path requests and Angular routes are now in the same scope / namespace, adds a prefix to all API calls, to distinguish the two services. Updates integration tests. (Also removes '/versions/' from API calls, to make the API vs Angular paths consistent.)
Before, the findOne methods assumed every request for a version / specification would succeed. When the user gave a non-existent specification ID, the server threw an exception, and 500 was returned to the client.
Now curl requests for …
=> API and Angular Routing fixes

backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/service/SpecificationDatabaseService.kt, frontend/src/app/specification-search-detail/specification-search-detail.component.html
If you make an empty text query, Lucene (the string searching engine) gives an uncaught exception, and a long stack trace in the kotlin logger. [Certain English words](https://stackoverflow.com/questions/13765698/getting-error-on-a-specific-query) are so common that they are filtered out of text search queries, so, more realistically: if the user's entire query was composed of them, this exception is also thrown.
Also, this now displays a message if nothing is found (either because the query was empty, or because no specification content matched the query) instead of the page just being blank. A user might incorrectly think they are awaiting results.
=> Add some error handling to search

backend/src/main/kotlin/com/tngtech/apicenter/backend/config/RestResponseExceptionHandler.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/service/SpecificationDatabaseService.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SharedRestControllerExceptions.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/VersionController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataService.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/exceptions/Exceptions.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataServiceTest.kt, frontend/src/app/specification-form/specification-form.component.ts
What were bad client requests (eg. no title given in an OpenAPI specification) were all eliciting 500 code responses from the server. This also printed long stack traces in the kotlin logger.
This uses Spring's `@ControllerAdvice` to return 4xx client error codes, with the added advantage of not printing stack traces. Some thrown exceptions are made more specific. (Also, this overrides the standard Spring error response object to have a more meaningful ISO timestamp, the default one is just an integer with no indication of how to interpret its value)
The error messages are all still returned and displayed to the client correctly in the frontend.
=> Add HTTP response codes with @ControllerAdvice

README.md
Waffle shuts down, so we're probably using a GitHub project
Signed-off-by: Fabian Winter <fabian.winter@tngtech.com>
=> Remove Waffle.io badge

backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/security/JwtAuthorizationFilter.kt, frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/app/auth/auth.guard.ts, frontend/src/app/auth/auth.service.ts, frontend/src/app/specification-overview/specification-overview.component.ts
Previously, the only check that Angular's authentication guard provided was that the string in `window.localStorage.token` was not null.
If a user sets the token to any random string (with the browser console), they bypass the guard, and can get to `/`. No specifications appear in the table, because the backend will reject the 'token' and so respond with Spring's 403 default response. However no error message is displayed; it simply looks as though no specifications have ever been uploaded.
This PR makes the guard _slightly_ more sophisticated. It decodes the current token, and checks the token's subject matches the username in local storage. Failure will redirect to `/login` again.
We cannot, client-side, verify that the token is signed correctly, because the HMAC secret stays …
=> Compare JWT subject in frontend authentication

frontend/src/app/auth/auth.guard.ts, frontend/src/app/login/login.component.ts
Previously, if an unauthenticated user requested a resource, they were redirected to `/login`, and after a successful login, were always redirected to `/`.
This change saves the initially requested URL, and redirects there after login.
=> Redirect to requested resource after login

backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataService.kt
A bug noticed when attempting to set an `x-api-id` as an integer, the application threw an uncaught exception and the file upload failed. Now the specification upload works as expected.
=> Fix for integer IDs

frontend/src/app/specification-store.service.ts, frontend/src/app/specification-version/graphiql-wrapper.component.ts, frontend/src/app/specification-version/specification-view.component.ts, frontend/src/app/specification-version/swagger-ui-wrapper.component.ts
In the VersionView component there was a direct `HttpClient.get` call, which is supposed to be abstracted away by the VersionService.
=> Replace usage of HttpClient outside of Service

backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceControllerIntegrationTest.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/mapper/converter/SpecificationEntityConverter.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/dto/SpecificationDto.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/dto/SpecificationFileDto.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/mapper/configurer/SpecificationFileDtoMappingConfigurer.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/mapper/converter/SpecificationFileDtoConverter.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/RemoteServiceUpdater.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataParser.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/entity/Specification.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceControllerUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/mapper/converter/SpecificationFileDtoConverterTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/service/RemoteServiceUpdaterTest.kt
#68 changed the `extractId` function to accept multiple data types, but accidentally removed the case when the file could not be parsed as JSON, and hence, no ID was extractable.
The try / catch block is reintroduced to avoid an uncaught exception causing the upload to fail.
***
#67 made the specification ID a required field in a version's metadata.
When uploading a GraphQL file, the user specifies certain fields of the metadata explicitly (namely title and version, because they cannot be derived from the file contents). But not the specification's ID, this is assigned server-side to a random UUID.
Because the metadata object used for file uploads (no ID) was not the same as the metadata object used in the domain layer (has ID, and cannot be null), Spring raised an …
=> Fix for file uploads with metadata

backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceController.kt, backend/src/main/resources/api-definition.json
Adds tags which were undefined. Removes status code responses which aren't served. Corrects specifying the required schema fields as a list and not in the properties section of the object.
Updates some parameters in the ServiceController that were overlooked previously.
=> Update Swagger file after renaming

README.md
Attempt to move the more technical / development-oriented content from the README to the wiki, and add information on how to run the docker image.
=> Make README friendlier

backend/src/main/resources/heroku.properties
Previously you could view and login to ApiCenter, but uploads would fail, returning from the backend an 500 Internal Server Error, root cause `org.postgresql.util.PSQLException: ERROR: column specificat1_.service_id does not exist`.
Assuming the column names in the code (in camelCase) were being converted inconsistently to snake_case, found a solution [here](https://stackoverflow.com/questions/25283198/spring-boot-jpa-column-name-annotation-ignored/38875123#38875123).
=> Fix Heroku deploy

backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceController.kt, frontend/src/app/specification-search-detail/specification-search-detail.component.html, frontend/src/app/specification-search-detail/specification-search-detail.component.ts, frontend/src/app/specification-search/specification-search.component.html, frontend/src/app/specification-search/specification-search.component.ts
Found when testing
Details:
- Corrects a method name that was accidentally skipped in the grand `Specification` -> `Service` renaming
- The test `services.length == 0` was occurring before the services list was defined, resulting in a frontend console error. Now there's a boolean to guard this field before the data comes through
- Pressing enter in an empty search box will not update the results or refresh the page
- If the user entered only characters that are filtered out by Spring's controllers (eg. just `#`, or ` `), so that the `@PathVariable` would end up blank, the route requested of the backend was `/api/v1/search/`. This is not matched by any controller, resulting in an uncaught server error. (Open to alternative suggestions on how to solve this than the one in this PR)
=> Small fixes to search functionality

frontend/src/app/login/login.component.html
When the page loads, the cursor starts off inside the username field, without requiring clicking on the box.
=> Autofocus username field

frontend/src/app/specification-form/specification-form.component.html, frontend/src/app/specification-form/specification-form.component.ts
Before, if an error prevented a file upload, the modal window would close, and the error message would be displayed in the body of the main page (above the buttons which open the file upload modals).
This change has the error appear inside the modal, and the modal remain open, making it simpler to adjust the form inputs so that the operation can eventually succeed.
=> Display error inside file upload modal

.travis.yml
We're actually using node 10, we just didn't tell Travis
=> Bump node for Travis

backend/src/main/kotlin/com/tngtech/apicenter/backend/config/RestResponseExceptionHandler.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationFileDownloader.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/exceptions/Exceptions.kt
Submitting something like "hello" to the remote file form causes an exception that wasn't part of the rest response exception handler, and so did not return an error message in a way the frontend could use:
`{"timestamp":1562056004073,"status":500,"error":"Internal Server Error","message":"no protocol: hello","path":"/api/v1/service"}`
This change also removes the string the user gave (ie. `location`) from the error message, because it already appears directly below in the form text box. (However it still might be useful for backend logging, so it's been left in the Exception constructors.)
=> Exception for malformed remote URL

frontend/src/app/app.module.ts, frontend/src/app/models/specificationfile.ts, frontend/src/app/specification-form/specification-form.component.html, frontend/src/app/specification-form/specification-form.component.ts, frontend/src/app/specification-overview/specification-overview.component.html
New versions can be uploaded without requiring `x-api-id` or a manually supplied id.
"id" was already an optional field in the `SpecificationFileDto` backend object. (Some integration tests use it.) This just populates it correctly in the frontend, when the user clicks on the upload button associated with a certain service.
=> Upload with service id in resource path

backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceControllerIntegrationTest.kt, backend/src/integration-test/resources/data.sql, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/entity/SpecificationEntity.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/mapper/converter/SpecificationEntityConverter.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/service/ServiceDatabase.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/dto/SpecificationFileDto.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/service/SpecificationDataParser.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/entity/Service.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/entity/Specification.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/handler/ServiceHandler.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceControllerUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/SpecificationControllerUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/mapper/converter/SpecificationFileDtoConverterTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/service/RemoteServiceUpdaterTest.kt, frontend/src/app/models/specification.ts, frontend/src/app/models/specificationfile.ts, frontend/src/app/service-store.service.spec.ts, frontend/src/app/specification-form/specification-form.component.ts, frontend/src/app/specification-overview/specification-overview.component.html, frontend/src/app/specification-overview/specification-overview.component.spec.ts, frontend/src/app/specification-overview/specification-overview.component.ts, frontend/src/app/specification-search-detail/specification-search-detail.component.spec.ts
Close #63 and close #64. Grouped these, as they are closely related when considering changes to the specification data model.
- The main version is that latest which is non-snapshot and non-prerelease, and only visible after expanding a table node in the overview
- When uploading a snapshot version, permit overriding of the specification content
=> Prereleases and snapshot versions

backend/build.gradle, backend/src/integration-test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceControllerIntegrationTest.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/config/ApiCenterProperties.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/config/Configuration.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/repository/ServiceRepository.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/database/service/ServiceDatabase.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceController.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/connector/rest/dto/ResultPageDto.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/entity/ResultPage.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/handler/ServiceHandler.kt, backend/src/main/kotlin/com/tngtech/apicenter/backend/domain/service/ServicePersistor.kt, backend/src/main/resources/META-INF/additional-spring-configuration-metadata.json, backend/src/main/resources/application.properties, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/rest/controller/ServiceControllerUnitTest.kt, backend/src/test/kotlin/com/tngtech/apicenter/backend/connector/service/ServiceDatabaseUnitTest.kt, frontend/src/app/models/service.ts, frontend/src/app/service-store.service.ts, frontend/src/app/specification-overview/specification-overview.component.css, frontend/src/app/specification-overview/specification-overview.component.html, frontend/src/app/specification-overview/specification-overview.component.ts, frontend/src/tsconfig.spec.json
Demo where the page size was set to 1 for a total of 3 services in the database
---
Update: Load pages on scroll (Again, page size is 1)
---
In `application.properties`, the user can set the page size with `apicenter.pageSize=N`, where it defaults to 10.
=> Pagination in specification overview

frontend/src/app/specification-form/specification-form.component.css, frontend/src/app/specification-form/specification-form.component.html
Also uses `<label>` elements instead of the placeholder text for describing form fields; semantic html is recommended for accessibility / screen readers.
Currently the metadata form looks like:
=> Make description field a textarea
